# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Surge

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '* * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update Sub Info
      run: |
        python ./update.py
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SUB_URL: ${{ secrets.SUB_URL }}
        
#     - name: Commit files
#       id: commit
#       run: |
#         git config --local user.email "action@github.com"
#         git config --local user.name "github-actions"
#         git add --all
#         if [-z "$(git status --porcelain)"]; then
#            echo "::set-output name=push::false"
#         else
#            git commit -m "Add changes" -a
#            echo "::set-output name=push::true"
#         fi
#       shell: bash
      
#     - name: Push changes
#       if: steps.commit.outputs.push == 'true'
#       uses: ad-m/github-push-action@master
#       with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
